version: "3.8"

services:
  app:
    container_name: dumbgpt-dev-c
    image: dumbgpt-dev-i
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
